### ISSUE TITLE
Errors while running!!

### ISSUE THREAD

**Issue by Tomhandson1029** [jason-li-831202/Vehicle-CV-ADAS#11]
[2023-10-04 21:25:55] [INFO] [Pycuda] Cuda Version: (12, 2, 0)
[2023-10-04 21:25:55] [INFO] [Driver] Cuda Version: 12020
[2023-10-04 21:25:55] [INFO] UfldDetector Model Type : UFLDV2_CULANE
[10/04/2023-21:25:59] _[TRT] [E] 3: [engine.cpp::nvinfer1::rt::Engine::getUserRegion::1312] Error Code 3: Internal Error (call of getBindingDimensions with invalid bindingIndex -1)_
[2023-10-04 21:25:59] [INFO] UfldDetector Type : [trt] || Version : [CUDAExecutionProvider]
[2023-10-04 21:25:59] [INFO] YoloDetector Model Type : YOLOV8
[2023-10-04 21:25:59] [INFO] YoloDetector Type : [trt] || Version : [CUDAExecutionProvider]
_Traceback (most recent call last):
  File "c:\Users\us\Desktop\Vehicle-CV-ADAS\demo.py", line 267, in <module>
    laneDetector.DetectFrame(frame)
  File "c:\Users\us\Desktop\Vehicle-CV-ADAS\TrafficLaneDetector\ultrafastLaneDetector\ultrafastLaneDetectorV2.py", line 271, in DetectFrame
    self.lanes_points, self.lanes_detected = self.process_output(output, self.cfg, original_image_width =  self.img_width, original_image_height = self.img_height)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\us\Desktop\Vehicle-CV-ADAS\TrafficLaneDetector\ultrafastLaneDetector\ultrafastLaneDetectorV2.py", line 426, in process_output
    return np.array(list(lanes_points.values())), list(lanes_detected.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part._
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------

**Comment by Tomhandson1029** [comment]
reply??

**Comment by jason-li-831202** [comment]
I think it's caused by the Python version. You can try downgrading the version.

**Comment by Tomhandson1029** [comment]
> 

I have the latest version python 3.11.5

**Comment by Tomhandson1029** [comment]
Yeah thanks it resolved but one problem is there 
**[TRT] [E] 3: [engine.cpp::nvinfer1::rt::Engine::getUserRegion::1312] Error Code 3: Internal Error (call of getBindingDimensions with invalid bindingIndex -1)**

**Comment by jason-li-831202** [comment]
I think that doesn't have much impact on the demo.

**Comment by Tomhandson1029** [comment]
> I think that doesn't have much impact on the demo.

ok but one more this the lane are not getting properly detected and fps is low
