### ISSUE TITLE
Update for yolov10 support

### ISSUE THREAD

**Issue by AekSW** [jason-li-831202/Vehicle-CV-ADAS#23]
Is it possible to use yolov10? I tried using it but it broke the utils for Bytetrack.

```
Traceback (most recent call last):
  File "C:\Projects\Vehicle-CV-ADAS-master\demo.py", line 304, in <module>
    objectTracker.DrawTrackedOnFrame(frame_show, False)
  File "C:\Projects\Vehicle-CV-ADAS-master\ObjectTracker\byteTrack\byteTracker.py", line 213, in DrawTrackedOnFrame
    self.plot_trajectories(frame, trajector , cid, tid)
  File "C:\Projects\Vehicle-CV-ADAS-master\ObjectTracker\core.py", line 195, in plot_trajectories
    color=self.class_colors[class_id],
KeyError: 'unknown'
```

What can I do to fix it? Will there be any update for yolov10 support?

**Comment by jason-li-831202** [comment]
YOLOv10 has added some post-processing parts compared to the previous YOLO series. Therefore, there are two ways to use it: either delete the original model's post-processing without converting it to ONNX, or write new post-processing for YOLOv10's output.

![image](https://github.com/jason-li-831202/Vehicle-CV-ADAS/assets/75941690/6cc90ce7-20aa-46f6-b5c4-4ae42e2ee4c5)
