### ISSUE TITLE
onxx file convert error !

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [jason-li-831202/Vehicle-CV-ADAS#27]
This is a terminal output : 

~/workspace/lane_tracking_detection_with_ai/Vehicle-CV-ADAS$ python3 convertOnnxToTensorRT.py -i /home/moveon2/workspace/lane_tracking_detection_with_ai/Vehicle-CV-ADAS/yolov8l.onnx -o /home/moveon2/workspace/lane_tracking_detection_with_ai/Vehicle-CV-ADAS/model.engine
Vehicle-CV-ADAS/convertOnnxToTensorRT: input_onnx_model=/home/moveon2/workspace/lane_tracking_detection_with_ai/Vehicle-CV-ADAS/yolov8l.onnx, output_trt_model=/home/moveon2/workspace/lane_tracking_detection_with_ai/Vehicle-CV-ADAS/model.engine, verbose=False
👉 Starting export with TensorRT Version :  10.0.1
[08/05/2024-11:05:51] [TRT] [I] [MemUsageChange] Init CUDA: CPU +18, GPU +0, now: CPU 24, GPU 750 (MiB)
[08/05/2024-11:05:52] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1763, GPU +312, now: CPU 1922, GPU 1062 (MiB)
Traceback (most recent call last):
  File "/home/moveon2/workspace/lane_tracking_detection_with_ai/Vehicle-CV-ADAS/convertOnnxToTensorRT.py", line 240, in <module>
    builder = EngineBuilder(verbose)
  File "/home/moveon2/workspace/lane_tracking_detection_with_ai/Vehicle-CV-ADAS/convertOnnxToTensorRT.py", line 114, in __init__
    self.config.max_workspace_size = int(workspace * (1 << 30))
AttributeError: 'tensorrt_bindings.tensorrt.IBuilderConfig' object has no attribute 'max_workspace_size'

How to solve this error ?

**Comment by jason-li-831202** [comment]
Please lower tensorrt version to 8.x.

**Comment by ahmet-f-gumustas** [comment]
I try soon. Thank You!
